// Package export generates shareable reports from probe session data.
package export

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/MuhammadHananAsghar/probe/internal/replay"
	"github.com/MuhammadHananAsghar/probe/internal/store"
)

// ComparisonMarkdown generates a markdown report for a two-request comparison.
func ComparisonMarkdown(c *replay.Comparison, version string) string {
	var sb strings.Builder

	sb.WriteString("# Probe — Request Comparison\n\n")
	sb.WriteString(fmt.Sprintf("Generated at %s by probe %s\n\n", time.Now().Format(time.RFC3339), version))

	sb.WriteString("## Requests\n\n")
	writeRequestSummary(&sb, "A", c.A)
	sb.WriteString("\n")
	writeRequestSummary(&sb, "B", c.B)
	sb.WriteString("\n")

	sb.WriteString("## Comparison\n\n")
	sb.WriteString("| Metric | A | B | Delta | Better |\n")
	sb.WriteString("|--------|---|---|-------|--------|\n")
	for _, row := range c.Metrics {
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
			row.Label, row.A, row.B, row.Delta, row.Better))
	}
	sb.WriteString("\n")

	if c.Summary != "" {
		sb.WriteString(fmt.Sprintf("**Summary:** %s\n\n", c.Summary))
	}

	// Response diff
	if c.A.ResponseContent != "" || c.B.ResponseContent != "" {
		sb.WriteString("## Responses\n\n")
		sb.WriteString("### A: " + c.A.Model + "\n\n")
		sb.WriteString("```\n")
		sb.WriteString(truncateMD(c.A.ResponseContent, 500))
		sb.WriteString("\n```\n\n")
		sb.WriteString("### B: " + c.B.Model + "\n\n")
		sb.WriteString("```\n")
		sb.WriteString(truncateMD(c.B.ResponseContent, 500))
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by [probe](https://github.com/MuhammadHananAsghar/probe) %s*\n", version))

	return sb.String()
}

// MultiComparisonMarkdown generates a markdown report for a multi-model comparison.
func MultiComparisonMarkdown(mr *replay.MultiResult, version string) string {
	var sb strings.Builder

	sb.WriteString("# Probe — Multi-Model Comparison\n\n")
	sb.WriteString(fmt.Sprintf("Generated at %s by probe %s\n\n", time.Now().Format(time.RFC3339), version))

	sb.WriteString("## Results\n\n")
	sb.WriteString("| Model | Provider | Cost | Latency | TTFT | Output Tokens | Badges |\n")
	sb.WriteString("|-------|----------|------|---------|------|---------------|--------|\n")
	for _, row := range mr.Table {
		badges := strings.Join(row.Badges, ", ")
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |\n",
			row.Model, row.Provider, row.Cost, row.Latency, row.TTFT, row.OutTokens, badges))
	}
	sb.WriteString("\n")

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by [probe](https://github.com/MuhammadHananAsghar/probe) %s*\n", version))

	return sb.String()
}

func writeRequestSummary(sb *strings.Builder, label string, req *store.Request) {
	sb.WriteString(fmt.Sprintf("### Request %s: #%d — %s (%s)\n\n", label, req.Seq, req.Model, req.Provider))
	sb.WriteString(fmt.Sprintf("- **Path:** `%s %s`\n", req.Method, req.Path))
	sb.WriteString(fmt.Sprintf("- **Status:** %d\n", req.StatusCode))
	sb.WriteString(fmt.Sprintf("- **Latency:** %s\n", formatDur(req.Latency)))
	sb.WriteString(fmt.Sprintf("- **Input tokens:** %d\n", req.InputTokens))
	sb.WriteString(fmt.Sprintf("- **Output tokens:** %d\n", req.OutputTokens))
	if req.PricingKnown {
		sb.WriteString(fmt.Sprintf("- **Total cost:** $%.8f\n", req.TotalCost))
	}
}

func formatDur(d time.Duration) string {
	ms := d.Milliseconds()
	if ms < 1000 {
		return fmt.Sprintf("%dms", ms)
	}
	return fmt.Sprintf("%.2fs", float64(ms)/1000)
}

func truncateMD(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "\n[truncated]"
}

// SessionMarkdown generates a Markdown summary report for an entire probe session.
func SessionMarkdown(requests []*store.Request, version string) string {
	var sb strings.Builder

	sb.WriteString("# Probe — Session Report\n\n")
	sb.WriteString(fmt.Sprintf("Generated at %s by probe %s\n\n", time.Now().Format(time.RFC3339), version))

	// Aggregate stats.
	var totalCost float64
	var totalLatency time.Duration
	var errorCount int
	modelCosts := make(map[string]float64)
	modelCounts := make(map[string]int)

	for _, r := range requests {
		totalCost += r.TotalCost
		totalLatency += r.Latency
		if r.StatusCode >= 400 || r.Status == store.StatusError {
			errorCount++
		}
		if r.PricingKnown {
			modelCosts[r.Model] += r.TotalCost
		}
		modelCounts[r.Model]++
	}

	avgLatencyMs := int64(0)
	if len(requests) > 0 {
		avgLatencyMs = totalLatency.Milliseconds() / int64(len(requests))
	}

	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Total requests | %d |\n", len(requests)))
	sb.WriteString(fmt.Sprintf("| Errors | %d |\n", errorCount))
	sb.WriteString(fmt.Sprintf("| Total cost | $%.6f |\n", totalCost))
	sb.WriteString(fmt.Sprintf("| Avg latency | %dms |\n", avgLatencyMs))
	sb.WriteString("\n")

	// Cost by model
	sb.WriteString("## Cost by Model\n\n")
	sb.WriteString("| Model | Requests | Total Cost |\n")
	sb.WriteString("|-------|----------|------------|\n")

	// Sort models by cost descending.
	type modelRow struct{ model string; cost float64; count int }
	rows := make([]modelRow, 0, len(modelCounts))
	for m, cnt := range modelCounts {
		rows = append(rows, modelRow{m, modelCosts[m], cnt})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].cost > rows[j].cost })
	for _, row := range rows {
		sb.WriteString(fmt.Sprintf("| %s | %d | $%.6f |\n", row.model, row.count, row.cost))
	}
	sb.WriteString("\n")

	// Top 5 most expensive requests.
	sb.WriteString("## Top 5 Most Expensive Requests\n\n")
	sb.WriteString("| # | Model | Provider | Cost | Latency | Tokens In/Out |\n")
	sb.WriteString("|---|-------|----------|------|---------|---------------|\n")

	sorted := make([]*store.Request, len(requests))
	copy(sorted, requests)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].TotalCost > sorted[j].TotalCost })
	limit := 5
	if len(sorted) < limit {
		limit = len(sorted)
	}
	for _, r := range sorted[:limit] {
		sb.WriteString(fmt.Sprintf("| #%d | %s | %s | $%.6f | %s | %d/%d |\n",
			r.Seq, r.Model, r.Provider, r.TotalCost, formatDur(r.Latency), r.InputTokens, r.OutputTokens))
	}
	sb.WriteString("\n")

	// Anomalies
	var anomalous []*store.Request
	for _, r := range requests {
		if len(r.Anomalies) > 0 {
			anomalous = append(anomalous, r)
		}
	}
	if len(anomalous) > 0 {
		sb.WriteString("## Anomalies Detected\n\n")
		for _, r := range anomalous {
			for _, a := range r.Anomalies {
				sb.WriteString(fmt.Sprintf("- **#%d** (%s): %s\n", r.Seq, a.Kind, a.Message))
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by [probe](https://github.com/MuhammadHananAsghar/probe) %s*\n", version))

	return sb.String()
}

// RequestMarkdown generates a per-request Markdown report.
func RequestMarkdown(r *store.Request, version string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Probe — Request #%d Report\n\n", r.Seq))
	sb.WriteString(fmt.Sprintf("Generated at %s by probe %s\n\n", time.Now().Format(time.RFC3339), version))

	writeRequestSummary(&sb, "", r)
	sb.WriteString("\n")

	if r.SystemPrompt != "" {
		sb.WriteString("## System Prompt\n\n")
		sb.WriteString("```\n")
		sb.WriteString(truncateMD(r.SystemPrompt, 1000))
		sb.WriteString("\n```\n\n")
	}

	if len(r.Messages) > 0 {
		sb.WriteString(fmt.Sprintf("## Messages (%d)\n\n", len(r.Messages)))
		for _, msg := range r.Messages {
			sb.WriteString(fmt.Sprintf("**%s:** %s\n\n", msg.Role, truncateMD(msg.Content, 500)))
		}
	}

	if len(r.ToolCalls) > 0 {
		sb.WriteString(fmt.Sprintf("## Tool Calls (%d)\n\n", len(r.ToolCalls)))
		for _, tc := range r.ToolCalls {
			sb.WriteString(fmt.Sprintf("- `%s(%s)`\n", tc.Name, truncateMD(tc.ArgumentsJSON, 200)))
		}
		sb.WriteString("\n")
	}

	if len(r.Anomalies) > 0 {
		sb.WriteString("## Issues Detected\n\n")
		for _, a := range r.Anomalies {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", a.Kind, a.Message))
		}
		sb.WriteString("\n")
	}

	if r.ResponseContent != "" {
		sb.WriteString("## Response\n\n")
		sb.WriteString("```\n")
		sb.WriteString(truncateMD(r.ResponseContent, 1000))
		sb.WriteString("\n```\n\n")
	}

	sb.WriteString("---\n")
	sb.WriteString(fmt.Sprintf("*Generated by [probe](https://github.com/MuhammadHananAsghar/probe) %s*\n", version))

	return sb.String()
}
